### ISSUE TITLE
Regex for "valid email" is broken!

### ISSUE THREAD

**Issue by RandalSchwartz** [VB10/kartal#4]
This is broken:

    final String emailRegex = r"^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+";

No, please don't use this so-called "regex email validation".

I can think of a few email addresses that are perfectly valid that do not match that regex. When you want to validate an email address, please do not use a hand-rolled (or even copy-n-pasted) regex. Instead, use https://pub.dev/packages/email_validator, which properly implements the RFC822 (et. seq.) address according to the rules in the RFC.

(Jokingly...) Or, cut-n-paste this one (and only this one): http://www.ex-parrot.com/~pdw/Mail-RFC822-Address.html. Don't forget to remove the newlines from that. :)

**Comment by VB10** [comment]
Right now, it's enough for us, may i'll add new regex for email
