### ISSUE TITLE
'appTheme' is deprecated and shouldn't be used. Use general. mediaQuery instead.

### ISSUE THREAD

**Issue by Renanuya** [VB10/kartal#47]
Deprem zamanındaki çekilmiş videoları izliyordum. [Video](https://youtu.be/jpy0geq3g1g?si=tT44w8Dd2avoVzZJ&t=1317)

Aşağıdaki kullanımda;
`Theme(data: context.appTheme.copyWith()`

Kullanımında **'appTheme' is deprecated and shouldn't be used. Use general. mediaQuery instead.** uyarısı veriyor fakat dökümanda ise **appTheme (ThemeData)** şeklinde yazıyor. 

**general.mediaQuery** kullandığımda ise **The argument type 'MediaQueryData' can't be assigned to the
parameter type 'ThemeData'** uyarısı alıyorum.

Ben mi yanlış kullanıyorum bilmiyorum çünkü yeni başladım sayılır yinede bildirmek istedim.

Görseller:
<img width="595" alt="image" src="https://github.com/VB10/kartal/assets/69991160/519f6d1c-1fb3-4f4d-9bdb-e039c72d497b">

-- 

<img width="588" alt="image" src="https://github.com/VB10/kartal/assets/69991160/0355fd1e-d48f-433d-8d40-7e0376f00e44">

--

<img width="487" alt="image" src="https://github.com/VB10/kartal/assets/69991160/3ca8abca-1f38-4f8a-acc9-5ad4e42a7f62">

**Comment by VB10** [comment]
context.general.appTheme seklinde kullanabilirsin @MehmetKaranlik bunuda ekleriz ara fixlerde

**Comment by Renanuya** [comment]
> context.general.appTheme seklinde kullanabilirsin @MehmetKaranlik bunuda ekleriz ara fixlerde

Tamamdır çok teşekkür ederim :) Kolay gelsin
