### ISSUE TITLE
Abstraction for launch maps and add custom map launch

### ISSUE THREAD

**Issue by E-MRE** [VB10/kartal#53]
https://github.com/VB10/kartal/blob/3a871f02015578e07344baeab88d688bf44d252b/lib/src/string_extension.dart#L149

Users may want to use yandex or another map. For this reason we can add custom launch settings in the method parameter. Also, if else statement not good for the call map opener. We need to create an abstract class for open map and also we can add a factory class for right instance.

**Comment by VB10** [comment]
@E-MRE you can send your request with PRRR :) i'm waiting thankss
