### ISSUE TITLE
After upgrading the package version from 3.5 to 4.0.2 compile breaking bug.

### ISSUE THREAD

**Issue by selim1238** [VB10/kartal#67]
Selam Veli Hocam.

Were using the package on Flutter Web side.
4.0.2 is breaking the compiling phase atm, I revert the version to 3.5 to solve the problem.

The problem I just faced after upgrading the package shown below;

```
Launching lib\main.dart on Chrome in debug mode...
/C:/Users/homem/AppData/Local/Pub/Cache/hosted/pub.dev/kartal-4.0.2/lib/src/file_extension.dart:24:43: Error: The getter 'path' isn't defined for the class 'File'.
 - 'File' is from 'dart:html'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'path'.
    final mimeType = lookupMimeType(_file.path);
                                          ^^^^
Failed to compile application.

Exited (1).
```

Flutter Version :  Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22631.3296], locale tr-TR)
Dart Version: Dart SDK version: 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "windows_x64"

Used Packages
 ```
firebase_auth:
cloud_firestore:
firebase_core: 
firebase_database: 
  
http: 

mobile_scanner: 
kartal: 

riverpod:
flutter_riverpod:

equatable: 
json_annotation: 

auto_route: 
```

not tested yet on a clean project I'll update the issue after testing.

**Comment by VB10** [comment]
@selim1238 hi bro
i found this issue then i added some fixes about this problem. could you check your project after i'll create new patch

`
  kartal:
    git: https://github.com/VB10/kartal
    ref: fix/file_type_platform
`

I'm waiting for your response thank you for feedback <3

**Comment by selim1238** [comment]
Fixed!, 
New file extension seems like fixed the issue. Thanks for the quick fix.

**Comment by VB10** [comment]
> Fixed!, 
> 
> New file extension seems like fixed the issue. Thanks for the quick fix.

I'll update with new version asap thanks again

**Comment by VB10** [comment]
@selim1238 you can use 4.0.3 version. i've published <3
